name: Deploy Next.js site to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch:  # Trigger manually from GitHub Actions UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAGES: true  # Set environment variable for GitHub Pages
    steps:
      - uses: actions/checkout@v4  # Checkout code
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use Node.js 20 for Next.js build
      - name: Install dependencies
        run: npm ci  # Install dependencies
      - name: Build and export
        run: npm run build  # Run Next.js build
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next  # Use Next.js static export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out  # Path to the exported static site

  deploy:
    needs: build  # Ensure build completes before deploying
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Deploy the site to GitHub Pages